---
title: "ppt"
author: "Simardeep Kaur"
date: "5/5/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Vision over Transit Incidents & Claims

-  Business Technology Services (BTS) and Insurance Claims groups of TransLink
-  May 8th,2020

## Business Question

- What are the patterns between different conditions of claims?

- What are the factors to avoid the incidences/claims that will eventually result in reducing the cost of insurance and claims?

## Research Questions

- What are the main predictors of frequency and severity of bus accidents?
- To what extent are different predictors and accident rates related?
- What factors are responsible for preventing claims?

## Data Dictionary

- Speed Performance
- Incident Operators
- Collisions (Preventable and Non- Preventable)

## Data product

- Reproducible Report
- Multiple hypothesis

## Multiple hypothesis

- Is the driver’s probation status related to accident rate?
- Is the APTA description related to more accident rates?
- Whether the model of the bus is related to incidents?
and many more...

## Methodoly

- Statistical Regression
- Cluster Analysis
- Exploratory Data Analysis(EDA)
- Predictive Models

## Rough Timeline

- 
## 



