library(tidyverse)

#' This function retrives a single value of a particular weather variable at a 
#' particular location on a particular day at a particular hour, given a list of pre-sorted data frames.
#'
#' @param location The location of interest to obtain weather data for. 
#' @param variable The weather variable of interest to build.
#' @param year_day The date of interest: should be in the format "yyyy-mm-dd"
#' @param stations_per_loc A named list, each item containing a presorted data frame (by distance 
#' from location) of weather data.
#' @param claims_line_data A data frame/tibble that contains the incident/no incident data that has columns
#' city_of_incident, describing the city_of_incident, describing the city of the incident,
#' a column named loss_date that gives the date of the incident, and the hour at which the incident/no incident
#' occurred. This is likely a tibble that is already generated by running 1_sample.R.
#'
#' @return A tibble with all of the weather data for a incident/no incident on the particular day and at 
#' the particular hour.
#' @export
#'
#' @examples
#' build_daily_series(
#' location = "Vancouver",
#' variables = c("temp", "pressure"),
#' stations_per_loc = stations_per_loc,
#' claims_line_data = my_simulated_incident_data
#' )
build_hourly_series <- function(location, variables, stations_per_loc, claims_line_data) {
  
  if (!is.character(location)) {
    stop("location must be a character (string) variable.")
  } else if (!is.character(variables)) {
    stop("variables must be a character (string) vector.")
  } else if (all(variables %in% colnames(stations_per_loc[[location]])) == FALSE) {
    stop("All variables given in the character vector variables must be a given column in stations_per_loc for each location.")
  } 
  
  location_only <- claims_line_data %>%
    filter(city_of_incident == {{location}}) %>%
    mutate(row_no = seq(1, nrow(.)))
  
  relevant_weather <- stations_per_loc[[location]] %>%
    select(date, hour, station_id, all_of(variables)) %>%
    mutate(hour = as.numeric(str_extract(hour, "^.{2}")))
  
  location_only_with_weather <- left_join(location_only, relevant_weather, by = c("loss_date" = "date", "hour_of_loss" = "hour")) %>%
    group_by(row_no, .drop = FALSE) %>%
    summarize_at(., .vars = variables, .funs = function(x) x %>% .[!is.na(.)] %>% .[1]) %>%
    select(-row_no)
  
  bind_cols(location_only, location_only_with_weather) %>%
    select(-row_no)
  
}

#' This function retrives a single value of a particular weather variable at a 
#' particular location and on a particular day, given a list of pre-sorted data frames.
#'
#' @param location The location of interest to obtain weather data for. 
#' @param variables The weather variables of interest to build.
#' @param stations_per_loc A named list, each item containing a presorted data frame (by distance 
#' from location) of weather data.
#' @param claims_line_data A data frame/tibble that contains the incident/no incident data that has columns
#' city_of_incident, describing the city_of_incident, describing the city of the incident,
#' and a column named loss_date that gives the date of the incident.
#' This is likely a tibble that is already generated by running 1_sample.R.
#'
#' @return A tibble with all of the relevant weather data for a particular incident/no incident
#' for a particular day.
#' @export
#'
#' @examples
#' build_daily_series(
#' location = "Vancouver",
#' variables = "mean_temp",
#' stations_per_loc = stations_per_loc,
#' claims_line_data = my_simulated_incident_data
#' )
build_daily_series <- function(location, variables, stations_per_loc, claims_line_data) {
  
  if (!is.character(location)) {
    stop("location must be a character (string) variable.")
  } else if (!is.character(variables)) {
    stop("variables must be a character (string) vector.")
  } else if (all(variables %in% colnames(stations_per_loc[[location]])) == FALSE) {
    stop("All variables given in the character vector variables must be a given column in stations_per_loc for each location.")
  } 
  
  location_only <- claims_line_data %>%
    filter(city_of_incident == {{location}}) %>%
    mutate(row_no = seq(1, nrow(.)))
  
  relevant_weather <- stations_per_loc[[location]] %>%
    select(date, station_id, all_of(variables)) 
  
  location_only_with_weather <- left_join(location_only, relevant_weather, by = c("loss_date" = "date")) %>%
    group_by(row_no, .drop = FALSE) %>%
    summarize_at(., .vars = variables, .funs = function(x) x %>% .[!is.na(.)] %>% .[1]) %>%
    select(-row_no)
  
  bind_cols(location_only, location_only_with_weather) %>%
    select(-row_no)
  
}