---
title: "interactive-report"
author: "Brayden Tang, Merve Sahin, Simardeep Kaur, Xugang Zhong"
date: "24/05/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(brms)
library(shiny)
library(tidyverse)
library(plotly)
library(ggthemes)
library(leaflet)
library(mapview)
library(tidyverse)
library(lubridate)
library(htmlwidgets)
```

# Introduction {.tabset}

Introductory text on report?

## Spatial Analysis of Incidents

```{r include= FALSE}
my_data <- read_csv("results/processed_data/new_dataset.csv")

ui <-  fluidPage(
  # Give the page a title
  titlePanel("Spatial Analysis for TransLink Incidents"),
  
  sidebarLayout(
    sidebarPanel(
      sliderInput("year", "Years", min(my_data$years), max(my_data$years),
              value = range(my_data$years), step= 1, sep = ""),
      br(),
      selectInput("experience", "Experience level of the operators",
                  choices = unique(na.omit(my_data$Experience_Category))),
      br(),
      plotOutput("plot", width = "100%", height = "200px")
      
    ),
     mainPanel(
       
       htmlOutput("summary"),
       br(),
       leafletOutput("map")
       ), 
))


 

server <- function (input, output) {
  
  year_data <- reactive({
    my_data %>% filter(years > input$year[1] & years < input$year[2])
  })
  
  output$map <- renderLeaflet({
    year_data() %>% 
      leaflet() %>%
      addProviderTiles("CartoDB.Positron", group = "Streets") %>% 
      addProviderTiles("Esri.WorldImagery", group = "Detailed") %>% 
      addProviderTiles("CartoDB.DarkMatter", group = "Dark") %>%
      setView(lng = -123.1171, lat = 49.2820, zoom = 12)
    
  })
  
  
  
  observe({
    
    experience <- input$experience
      pal <- colorFactor(palette = "viridis", domain = NULL)
      colors = rgb(t(col2rgb(palette())) / 255)
    
    sub_data <- year_data() %>% 
      filter(year_data()$Experience_Category == experience)
    
    leafletProxy("map") %>% clearControls() %>% clearMarkers() %>% 
      addCircleMarkers(lng = jitter(sub_data$long, factor = 0.1),
                       lat = jitter(sub_data$lat, factor = 0.1),
                       #stroke = FALSE, fillOpacity = 0.5, radius = 3,
                       color = pal(sub_data$cost_range),
                       #clusterOptions = markerClusterOptions(maxClusterRadius = 1),
                       radius=3, # Total count
                       stroke=FALSE, # Circle stroke
                       fillOpacity=0.5,
                       popup=paste0("<b>", sub_data$apta_desc, "</b> <br>",
                                    "<b>", "Date: ", "</b> ", sub_data$loss_date, "<br>",
                                    "<b>", "Cost: ", "</b>$", sub_data$`paid_cost$`, "<br>",
                                    "<b>", "Employee Id: ", "</b> ", sub_data$employee_id, "<br>",
                                    "<b>", "Bus Age: ", "</b> ", sub_data$bus_age, "<br>",
                                    "<b>","Manufacturer: ", "</b> ", sub_data$asset_manufacturer, "<br>" ),
                       #popupOptions = popupOptions(closeOnClick = TRUE),
      ) %>% leaflet::addLayersControl(baseGroups = c('Streets','Detailed', "Dark"),
                                      options = layersControlOptions(collapsed = FALSE)) %>% 
      addLegend(data = sub_data,"bottomleft", 
                pal = pal,
                # colors = colors,
                values = ~cost_range,
                title = "Cost Levels", 
                opacity = .9)
  
  })
  
  output$summary <- renderText({
    updated_data <- year_data() %>% 
      filter(year_data()$Experience_Category == input$experience)
    
    paste("<b>Summary: </b>", "<br>",
      "There are " , dim(updated_data)[1], " incidents between these years.")
  })

  # output$plot1 <- renderPlot({
  #   updated_data <- year_data() %>% 
  #     filter(year_data()$Experience_Category == input$experience)
  #   # Add a little noise to the cars data
  #   # p <- updated_data %>% filter(bus_age > -1  & bus_age < 30 ) %>% 
  #   #   ggplot(aes(bus_age)) +geom_histogram(bins = 20) +
  #   #   labs(title = "The distribution of bus age", 
  #   #        x = 'bus age', 
  #   #        y = 'number of incidents')
  #   # p + theme_economist()
  #   p1 <- updated_data %>% ggplot(aes(city_of_incident)) + geom_bar()+ theme(axis.text.x = element_text(angle = 90)) +
  #     labs(title = "The number of incidents in different cities",
  #          x = '',
  #          y = 'number of incidents') 
  #   p1 + theme_economist()
  # })
  output$plot <- renderPlot({
    updated_data <- year_data() %>% 
      filter(year_data()$Experience_Category == input$experience)
    updated_data %>% filter(bus_age > -1  & bus_age < 30 ) %>%
      ggplot(aes(bus_age)) +geom_histogram(bins = 20) +
      labs(title = "The Distribution of Bus Ages",
           x = 'Bus Age',
           y = 'Number of Incidents') + theme_economist_white()
    
  })
}

```

```{r , echo = FALSE}
shinyApp(ui, server)
```

## Operator Analysis

METHODOLOGY/More analysis that was carried out (tables probably)

### Predictive Analysis

```{r Operator Analysis: Import, include = FALSE}

best_bayes_model <- readRDS("results/operators/models/best-bayes-model.rds")
posterior_predictions <- readRDS("results/operators/report-tables/posterior_samples.rds")

posterior_samples <- as_tibble(posterior_predictions$posterior_samples, .name_repair = "unique") %>% set_names(seq(1, ncol(.), 1))

predictor_combinations <- posterior_predictions$variables %>%
  mutate(
    experience = as.character(experience),
    cost_centre = as.character(cost_centre)
    )

predictor_combinations$experience <- ifelse(predictor_combinations$experience == ">6 & 18 Months", ">6 & <18 Months", predictor_combinations$experience)
rm(posterior_predictions)

marginal_plot <- conditional_effects(best_bayes_model, probs = c(0.05, 0.95))[[1]] %>%
  select(effect1__, estimate__, lower__, upper__) %>%
  set_names(c("Effect", "Estimate", "Lower", "Upper")) %>%
  mutate(Effect = as.character(Effect)) %>%
  mutate(Effect = as.factor(ifelse(Effect == ">6 & 18 Months", ">6 & <18 Months", Effect))) %>%
  mutate(Effect = fct_relevel(Effect, c("<6 Months", ">6 & <18 Months", ">18 & <60 Months", ">60 Months")))

random_effects <- ranef(best_bayes_model, summary = FALSE)$cost_centre
pop_effect <- fixef(best_bayes_model, summary = FALSE) 

calculate_plotting_stats <- function(col_num) {

  if (col_num == 1) {
    data_re <- as_tibble(pop_effect[, 1] + random_effects[, , 1])
  } else {
    data_re <- as_tibble(pop_effect[, 1] + random_effects[, , 1] + pop_effect[, col_num] + random_effects[, , col_num])
  }

  plotting_data <- tibble(
      `Cost Centre` = colnames(random_effects[, , col_num]),
      Estimate = round(exp(apply(data_re, 2,  FUN = median)), 3),
      `Lower 5%` = round(exp(apply(data_re, 2, FUN = function(x) quantile(x, 0.05))), 3),
      `Upper 95%` = round(exp(apply(data_re, 2, FUN = function(x) quantile(x, 0.95))), 3)
    ) %>%
    mutate(`Cost Centre` = fct_reorder(`Cost Centre`, Estimate, min))
  if (col_num == 1) {
    pop_effect_opt <- tibble(`Global Effect` = round(exp(median(pop_effect[, 1])), 3))
  } else {
    pop_effect_opt <- tibble(`Global Effect` = round(exp(median(pop_effect[, 1] + pop_effect[, col_num])), 3))
  }
  list(plot_data = plotting_data, vline = pop_effect_opt)
}

```

```{r Operator Analysis: Plot, echo = FALSE, warning = FALSE}

selectInput("cost_centre_oa", label = "Cost Centre:", 
            choices = unique(predictor_combinations$cost_centre), selected = "VTC")
selectInput("experience_oa", label = "Experience Level:",
            choices = unique(predictor_combinations$experience), selected = ">60 Months")

 
renderPlotly({
  
  row_val <- which(input$cost_centre_oa == predictor_combinations$cost_centre & input$experience_oa == predictor_combinations$experience)
  
  median_samp <- median(posterior_samples[, row_val] %>% pull())
  lower <- quantile(posterior_samples[, row_val] %>% pull(), 0.05)
  upper <- quantile(posterior_samples[, row_val] %>% pull(), 0.95)
  
  plotting_data_oa <- posterior_samples[, row_val] %>%
    set_names("Number of Incidents/Yr") %>%
    mutate(`Number of Incidents/Yr` = as.character(`Number of Incidents/Yr`)) %>%
    group_by(`Number of Incidents/Yr`) %>%
    count() %>%
    ungroup() %>%
    mutate(`Probability of Occurring` = round(n / sum(n), 2))
  
  total_gte8 <- sum(plotting_data_oa$`Probability of Occurring`[plotting_data_oa$`Number of Incidents/Yr` >= 8])
  
  plotting_data_oa <- plotting_data_oa %>%
    filter(`Number of Incidents/Yr` %in% seq(1, 7, 1)) %>%
    bind_rows(tibble(`Number of Incidents/Yr` = '8+', n = NA, `Probability of Occurring` = total_gte8))
  
  ggplotly(ggplot(data = plotting_data_oa, aes(x = `Number of Incidents/Yr`, y = `Probability of Occurring`)) +
  geom_bar(stat = "identity") +
  labs(x = "Incidents/Year", y = "Probability of Occurring") +
  theme_economist() +
  theme(
      axis.title.y = element_text(vjust = 5),
      axis.title.x = element_text(vjust = -3)) +
  scale_x_discrete(drop = FALSE), autosize = TRUE) %>%
    layout(title = list(text = paste0("Experience: ", input$experience_oa, ", Cost Centre: ", input$cost_centre_oa, "<br>", "<sup>", "Median: ", round(median_samp, 2), ", 90% Credible Interval: ", "[" , round(lower, 2), ", ", round(upper, 2), "]", "</sup>"), x = 0))
  
  })

```

DESCRIPTION AND INTERPRETATION

### Effect Analysis 

```{r Operator Analysis: Marginal Effects, echo = FALSE, warning = FALSE}

tabsetPanel(
  tabPanel("Random Effects", selectInput("experience_oa_re", label = "Experience:", 
            choices = unique(predictor_combinations$experience), selected = ">60 Months"), plotlyOutput("re_plot")),
  tabPanel("Fixed Effects",
           selectInput(
             "cost_centre_oa_re",
             label = "Cost Centre:",
             choices = c(unique(predictor_combinations$cost_centre), "All"),
             selected = "All"),
  plotlyOutput("fe_plot"))
)

output$fe_plot <- renderPlotly({
  
  cost_centre_sel <- input$cost_centre_oa_re

  if (cost_centre_sel != "All") {
      intercept <- pop_effect[, 1] + random_effects[, cost_centre_sel, 1]
      effects_per_centre <- cbind(intercept, intercept + pop_effect[, 2:4] + random_effects[, cost_centre_sel, 2:4])
  } else {
    intercept <- pop_effect[, 1]
    effects_per_centre <- cbind(intercept, (pop_effect + intercept)[, 2:4])
  }
  plot_cost_sel <- tibble(
    Estimate = round(exp(apply(effects_per_centre, 2, median)), 3),
    Experience = as.factor(c(">60 Months", "<6 Months", ">18 & <60 Months", ">6 Months & <18 Months")),
    `Lower 5%` = round(exp(apply(effects_per_centre, 2, function(x) quantile(x, 0.05))), 3),
    `Upper 95%` = round(exp(apply(effects_per_centre, 2, function(x) quantile(x, 0.95))), 3)
  ) %>%
    mutate(Experience = fct_relevel(Experience, c("<6 Months", ">6 Months & <18 Months", ">18 & <60 Months", ">60 Months")))
    
  
  ggplotly(ggplot(plot_cost_sel, aes(x = Experience, y = Estimate, ymin = `Lower 5%`, ymax = `Upper 95%`)) +
  geom_point() + 
  geom_errorbar(aes(ymin = `Lower 5%`, ymax = `Upper 95%`)) +
  theme_economist() +
  labs(x = "Experience Level", y = "Estimated Incidents/Yr"), width = 800, autosize = TRUE) %>%
  layout(title = list(text = paste0("Estimated Incidents/Yr Per Experience", "<br>", "<sup>", "Cost Centre: ", cost_centre_sel, "</sup>"), x = 0)) 
  
  })

output$re_plot <- renderPlotly({

  if (input$experience_oa_re == ">60 Months") {
    
    plotting_data <- calculate_plotting_stats(1)
    
  } else if (input$experience_oa_re == "<6 Months") {
    
    plotting_data <- calculate_plotting_stats(2)
    
  } else if (input$experience_oa_re == ">18 & <60 Months") {
    
    plotting_data <- calculate_plotting_stats(3)
    
  } else {
    
    plotting_data <- calculate_plotting_stats(4)
    
  }
  
  ggplotly(ggplot(plotting_data[[1]], aes(x = `Cost Centre`, y = Estimate, ymin = `Lower 5%`, ymax = `Upper 95%`)) +
    geom_point() + 
    geom_errorbar(aes(ymin = `Lower 5%`, ymax = `Upper 95%`), width = 0) +
    geom_hline(data = plotting_data[[2]], aes(yintercept = `Global Effect`), color = "red") + 
    coord_flip() +
    labs(y = "Estimated Incidents/Yr") + 
    theme_economist() +
    theme(axis.title.y = element_blank())) %>%
    layout(title = list(text = paste0("Estimated Cost Centre Effects for: ", input$experience_oa_re, "<br>", "<sup>", "Global Effect in Red", "</sup>"), x = 0)) 
  
  })
```

DESCRIPTION AND INTERPRETATION